export const FooterArray: string[] = [
    'Operating on a no-win, no-fee basis',
    'UK high-street banks are paying £Millions',
    'Simple, quick & free to complete',
]

export const BanksAndLenderArray: string[] = [
    'HSBC Bank',
    'M&S Bank',
    'Barclays',
    'Barclaycard',
    'Egg (Barclaycard)',
    'Goldfish',
    'Lloyds',
    'Halifax Bank of Scotland',
    'Black Horse',
    'MBNA',
    'Liverpool Victoria',
    'Captial One',
    'Santander (Credit Card & Loans)',
    'JD Williams & Company Limited',
    'Alliance & Leicester (Loans)',
    'FirstPlus Finanical',
    'John Lewis',
    'First Direct',
    'Littlewoods',
    'Sainsburys Bank',
    'Santander (Store Cards)',
    'Shop Direct Finance Company Limited',
    'Freemans PLC',
    'Grattan PLC',
    'Argos',
    'The Co-Operative Bank',
]
